default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql5.7.x
  username: root
  password: 
  host: localhost
  database: mysql8001.xserver.jp

test:
  <<: *default
  adapter: mysql5.7.x
  username: root
  password: 
  host: localhost
  database: mysql8001.xserver.jp

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>

  