default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql5.7
  username: root
  password: EeDn9TB94hIm
  host: localhost
  database: http://abest.xsrv.jp/doc

test:
  <<: *default
  adapter: mysql5.7
  username: root
  password: EeDn9TB94hIm
  host: localhost
  database: http://abest.xsrv.jp/doc

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['http://abest.xsrv.jp/doc'] %>


