default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql5.7
  username: root
  password: EeDn9TB94hIm
  host: localhost
  database: mysql8001.xserver.jp

test:
  <<: *default
  adapter: mysql5.7
  username: root
  password: EeDn9TB94hIm
  host: localhost
  database: mysql8001.xserver.jp

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['mysql8001.xserver.jp'] %>


