default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password: 
  host: localhost
  database: postgres://abest_design_user:r6p4CvYa671RTypwz9rl8lDbGloC0RqZ@dpg-cfm6ut2rrk07m3s7evug-a/abest_design

test:
  <<: *default
  adapter: mysql2
  username: root
  password: 
  host: localhost
  database: postgres://abest_design_user:r6p4CvYa671RTypwz9rl8lDbGloC0RqZ@dpg-cfm6ut2rrk07m3s7evug-a/abest_design

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>